# Generated by Django 4.1.5 on 2023-01-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("location", models.CharField(blank=True, max_length=50, null=True)),
                ("contact_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[("Local", "Local"), ("Foreign", "Foreign")],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
