# Generated by Django 4.1.5 on 2023-01-20 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_remove_stock_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "image",
                    models.ImageField(default="product.png", upload_to="category_pics"),
                ),
                ("receipt_no", models.CharField(blank=True, max_length=50, null=True)),
                ("item_description", models.TextField(blank=True, null=True)),
                ("quantity", models.IntegerField(blank=True, default="0", null=True)),
                (
                    "returned_quantity",
                    models.IntegerField(blank=True, default="0", null=True),
                ),
                (
                    "unit_returned_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_returned_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "sale_quantity",
                    models.IntegerField(blank=True, default="0", null=True),
                ),
                (
                    "delivery_quantity",
                    models.IntegerField(blank=True, default="0", null=True),
                ),
                (
                    "yet_to_deliver",
                    models.IntegerField(blank=True, default="0", null=True),
                ),
                (
                    "waybill_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("sale_by", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "unit_sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Credit", "Credit"),
                            ("Full Payment", "Full Payment"),
                            ("Part Payment", "Part Payment"),
                            ("Take Balance", "Take Balance"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.category",
                    ),
                ),
                (
                    "returned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="inventory.customers",
                    ),
                ),
                (
                    "sale_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="history_sale_to",
                        to="inventory.customers",
                    ),
                ),
            ],
        ),
    ]
