# Generated by Django 4.1.5 on 2023-01-21 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_cash_cashhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cash",
            name="issue_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="paid_by",
                to="inventory.customers",
            ),
        ),
    ]
